name: Create VM (Azure)
on:
 workflow_dispatch:        
# push:                                             #  workflow_dispatch for manually triggered
#   branches: [ master ]
jobs:
  provision:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      #  az group create -n rg-gha -l "${{ inputs.region }}"
      - name: Create VM
        run: |
          az group create -n rg-gha -l "northeurope"
          az vm create -g rg-gha -n gha-vm --image Ubuntu2204 --size "Standard_B2s" --admin-username ghadmin --generate-ssh-keys
