name: Create VM (Azure)
on:
  workflow_dispatch:
    inputs:
      vmSize: { required: true, type: string }
      region: { required: true, type: string }
jobs:
  provision:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create VM
        run: |
          az group create -n rg-gha -l "${{ inputs.region }}"
          az vm create -g rg-gha -n gha-vm --image Ubuntu2204 --size "${{ inputs.vmSize }}" --admin-username ghadmin --generate-ssh-keys
